const $=id=>document.getElementById(id);const groups=Array.from({length:36},(_,i)=>({id:String(-1001000000-i),title:['Design Community','Startup Indonesia','Developer Hub','Web Builders','UI Inspiration','Node.js Indonesia','Open Source Lab','Digital Creator','Product Talk','Tech Daily','Frontend Circle','Backend Friends'][i%12]+' '+String(i+1).padStart(2,'0'),blacklisted:i%13===0}));
const selected=()=>[...document.querySelectorAll('.gcheck:checked')].map(x=>x.value);const safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function activity(text){const box=$('activityList');if(box.querySelector('.empty'))box.innerHTML='';const row=document.createElement('div');row.className='activity-item';row.innerHTML='<i class="activity-dot"></i><div><b>'+safe(text)+'</b><small>'+new Date().toLocaleTimeString()+'</small></div>';box.prepend(row)}
function update(){const n=selected().length;$('count').textContent=n+' dipilih';$('statSelected').textContent=n;$('chars').textContent=$('text').value.length;$('draftState').textContent='Unsaved'}
function render(){const q=$('search').value.toLowerCase();$('groups').innerHTML=groups.filter(g=>g.title.toLowerCase().includes(q)).map(g=>'<label class="group"><input class="gcheck" type="checkbox" value="'+safe(g.id)+'" '+(g.blacklisted?'disabled':'')+'><div class="avatar">'+safe(g.title[0])+'</div><div class="group-copy"><b>'+safe(g.title)+'</b><small>'+(g.blacklisted?'Excluded':'Available target')+'</small></div><span class="check-dot"></span></label>').join('')||'<div class="empty"><b>Tidak ditemukan</b><span>Coba kata kunci lain.</span></div>';document.querySelectorAll('.gcheck').forEach(x=>x.onchange=update);update()}
function selectAll(){document.querySelectorAll('.gcheck:not(:disabled)').forEach(x=>x.checked=true);update();activity('Semua target yang tersedia dipilih');$('status').textContent='Semua target tersedia dipilih.'}function clearAll(){document.querySelectorAll('.gcheck').forEach(x=>x.checked=false);update();activity('Selection dibersihkan')}
function saveDraft(){localStorage.ubotDraft=JSON.stringify({text:$('text').value,delay:$('delay').value});$('draftState').textContent='Saved';$('status').textContent='Draft tersimpan.';activity('Draft disimpan di browser')}function loadDraft(){try{const d=JSON.parse(localStorage.ubotDraft||'{}');if(d.text)$('text').value=d.text;if(d.delay)$('delay').value=d.delay;$('draftState').textContent='Saved';update()}catch{}}
function exportSettings(){const data={delay:$('delay').value,theme:localStorage.theme||'light',draft:localStorage.ubotDraft||null};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='ubot-settings.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);activity('Settings diekspor')}
$('search').oninput=render;$('text').oninput=update;$('selectAll').onclick=selectAll;$('clearAll').onclick=clearAll;$('refresh').onclick=()=>{render();activity('Target list direfresh')};$('saveDraft').onclick=saveDraft;$('loadDraft').onclick=loadDraft;$('exportSettings').onclick=exportSettings;
$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light';$('theme').textContent=document.body.classList.contains('dark')?'☀':'☾'};if(localStorage.theme==='dark'){document.body.classList.add('dark');$('theme').textContent='☀'}
$('send').onclick=()=>{const ids=selected(),text=$('text').value.trim();if(!text)return $('status').textContent='Pesan masih kosong.';if(!ids.length)return $('status').textContent='Pilih minimal satu target.';if(!$('consent').checked)return $('status').textContent='Konfirmasi target terlebih dahulu.';if(!$('dryRun').checked){$('status').textContent='Frontend-only: mode pengiriman dinonaktifkan tanpa backend Telegram.';activity('Pengiriman diblokir: frontend-only mode');return}$('progressBar').style.width='100%';$('summary').textContent='100%';$('status').textContent='Preview selesai — tidak ada pesan dikirim.';$('log').textContent=ids.map(id=>'PREVIEW • '+id).join('\n');activity('Preview broadcast untuk '+ids.length+' target')};
addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;$('scrollProgress').style.width=(h>0?(scrollY/h)*100:0)+'%'});$('up').onclick=()=>scrollTo({top:0,behavior:'smooth'});$('down').onclick=()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'smooth'});loadDraft();render();$('statGroups').textContent=groups.filter(x=>!x.blacklisted).length;
