async function requireAuth(){try{const r=await fetch('/api/auth?action=me');if(!r.ok)throw 0;const d=await r.json();document.body.dataset.user=d.user?.username||'';const u=document.getElementById('userName');if(u)u.textContent=d.user?.username||'User'}catch{location.replace('/login')}}
async function logout(){await fetch('/api/auth?action=logout',{method:'POST'});location.replace('/login')}
let groups=[];
const $=id=>document.getElementById(id);
const selected=()=>[...document.querySelectorAll('.gcheck:checked')].map(x=>x.value);
const safe=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]));
function update(){const n=selected().length;$('count').textContent=`${n} dipilih`;$('statSelected').textContent=n;$('chars').textContent=$('text').value.length;$('draftState').textContent='Unsaved'}
function render(){const q=$('search').value.toLowerCase();$('groups').innerHTML=groups.filter(g=>(g.title||'').toLowerCase().includes(q)).map(g=>`<label class="group"><input class="gcheck" type="checkbox" value="${safe(g.id)}" ${g.blacklisted?'disabled':''} onchange="update()"><div class="avatar">${safe((g.title||'?').slice(0,1).toUpperCase())}</div><div class="group-copy"><b>${safe(g.title)}</b><small>${g.blacklisted?'Excluded':'Available target'}</small></div><span class="check-dot"></span></label>`).join('')||'<div class="empty"><div>⌕</div><b>Tidak ditemukan</b><span>Coba kata kunci lain.</span></div>';update()}
async function api(path,opt={}){const key=$('key').value.trim();if(!key)throw Error('Bridge key belum diisi.');const r=await fetch('/api/bridge'+path,{...opt,headers:{'Content-Type':'application/json','X-Bridge-Key':key}});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw Error(d.error||'Request gagal');return d}
async function loadGroups(){try{$('bridgeStatus').textContent='Connecting...';$('statState').textContent='Loading';const d=await api('/groups');groups=d.groups||[];$('statGroups').textContent=groups.length;render();$('status').textContent=`${groups.length} grup tersedia.`;$('bridgeStatus').textContent='Bridge online';$('statState').textContent='Ready'}catch(e){$('bridgeStatus').textContent='Bridge offline';$('status').textContent='❌ '+e.message;$('statState').textContent='Error'}}
function selectAll(){document.querySelectorAll('.gcheck:not(:disabled)').forEach(x=>x.checked=true);update();$('status').textContent=`✓ Semua target yang tersedia dipilih (${selected().length}).`}
function clearAll(){document.querySelectorAll('.gcheck').forEach(x=>x.checked=false);update()}
function saveDraft(){localStorage.ubotDraft=JSON.stringify({text:$('text').value,delay:$('delay').value});$('draftState').textContent='Saved';$('status').textContent='✓ Draft tersimpan di browser.'}
function loadDraft(){try{const d=JSON.parse(localStorage.ubotDraft||'{}');if(d.text)$('text').value=d.text;if(d.delay)$('delay').value=d.delay;update();$('draftState').textContent='Saved'}catch{}}
function exportConfig(){const data={delay:$('delay').value,theme:localStorage.theme||'light',draft:localStorage.ubotDraft||null};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='ubot-settings.json';a.click();URL.revokeObjectURL(a.href)}
$('search').oninput=render;$('text').oninput=update;$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light';$('theme').textContent=document.body.classList.contains('dark')?'☀':'☾'};
if(localStorage.theme==='dark'){document.body.classList.add('dark');$('theme').textContent='☀'}
$('send').onclick=async()=>{const text=$('text').value.trim(),ids=selected();if(!text)return $('status').textContent='❌ Pesan masih kosong.';if(!ids.length)return $('status').textContent='❌ Pilih minimal satu grup.';if(!$('consent').checked)return $('status').textContent='❌ Aktifkan konfirmasi bahwa target mengizinkan pesan.';if($('dryRun').checked){$('progressBar').style.width='100%';$('summary').textContent=`Preview ${ids.length} target`;$('log').textContent=ids.map(id=>`PREVIEW • ${id}`).join('\n');$('status').textContent='✓ Dry run selesai — tidak ada pesan yang dikirim.';return}$('send').disabled=true;$('statState').textContent='Sending';$('progressBar').style.width='15%';$('status').textContent='⏳ Memproses...';try{const d=await api('/broadcast',{method:'POST',body:JSON.stringify({text,groupIds:ids,delayMs:Number($('delay').value),consent:true})});const pct=d.total?Math.round(d.sent/d.total*100):100;$('progressBar').style.width=pct+'%';$('summary').textContent=`${d.sent}/${d.total} berhasil`;$('log').textContent=(d.results||[]).map(x=>`${x.ok?'✓':'×'} ${x.id}${x.error?' — '+x.error:''}`).join('\n')||'Tidak ada target.';$('status').textContent='✓ Proses selesai.';$('statState').textContent='Done'}catch(e){$('progressBar').style.width='0';$('status').textContent='❌ '+e.message;$('statState').textContent='Error'}finally{$('send').disabled=false}};
$('saveDraft').onclick=saveDraft;$('loadDraft').onclick=loadDraft;$('exportSettings').onclick=exportConfig;loadDraft();

requireAuth();
